// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DevinuxVSIXGenerator
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidDevinuxVSIXGeneratorPackageString = "94b7ee34-2d2d-435f-a20a-4ea0bd39677e";
        public static Guid guidDevinuxVSIXGeneratorPackage = new Guid(guidDevinuxVSIXGeneratorPackageString);

        public const string guidDevinuxVSIXGeneratorPackageCmdSetString = "5be1864c-4c5d-44cd-b147-50b40b38c8e4";
        public static Guid guidDevinuxVSIXGeneratorPackageCmdSet = new Guid(guidDevinuxVSIXGeneratorPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int DevinuxMenuGroup = 0x1000;
        public const int DevinuxMenuSubmenu = 0x1001;
        public const int GroupDddMain = 0x2001;
        public const int GroupDddCqrsApplication = 0x2002;
        public const int GroupDddCqrsPersistence = 0x2003;
        public const int GroupDddCqrsInterface = 0x2004;
        public const int CreateDDDFolders = 0x1003;
        public const int CreateApplicationService = 0x1004;
        public const int CreateApplicationInterface = 0x1005;
        public const int CreateApplicationMapper = 0x1006;
        public const int CreateApplicationModel = 0x1007;
        public const int CreatePersistenceDbContext = 0x1008;
        public const int CreatePersistenceDbContextInterface = 0x1009;
        public const int CreatePersistenceInterface = 0x1010;
        public const int CreatePersistenceRepository = 0x1011;
        public const int CreateApiController = 0x1012;
        public const int CreateApiModel = 0x1013;
        public const int CreateApiMapper = 0x1014;
        public const int CreateModelRefactor = 0x3000;
    }
}